define([], function() {
  return {
    "PropertyPaneDescription": "Aanvraag ",
    "BasicGroupName": "Basis Eigenschappen",
    "TargetListFieldLabel": "Bron Lijst",

    "YesText": "Ja",
    "NoText": "Nee",

    "RequestTypeFieldLabel": "Kies een Aanvraag Type voor Persoonlijke Data",
    "RequestTypeAccessLabel": "Toegang",
    "RequestTypeCorrectLabel": "Correctie",
    "RequestTypeExportLabel": "Export",
    "RequestTypeObjectionLabel": "Bezwaar",
    "RequestTypeEraseLabel": "Verwijderen",

    "TitleFieldLabel": "Titel",
    "TitleFieldPlaceholder": "Geef de titel voor de aanvraag",
    "TitleFieldValidationErrorMessage": "De titel moet minimaal 10 tekens lang zijn",
    "DataSubjectFieldLabel": "Data Subject",
    "DataSubjectFieldPlaceholder": "Provide a target Data Subject",
    "DataSubjectEmailFieldLabel": "Data Subject Email",
    "DataSubjectEmailFieldPlaceholder": "Provide a valid email address for the Data Subject",
    "DataSubjectEmailFieldValidationErrorMessage": "Please, provide a valid email address",
    "VerifiedDataSubjectFieldLabel": "Verified Data Subject",
    "RequestAssignedToFieldLabel": "Request Assigned To",
    "RequestAssignedToFieldPlaceholder": "Provide the assignee for the Request",
    "RequestInsertionDateFieldLabel": "Request Insertion Date",
    "RequestInsertionDateFieldPlaceholder": "Provide the Insertion Date of the Request",
    "RequestDueDateFieldLabel": "Request Due Date",
    "RequestDueDateFieldPlaceholder": "Provide the Due Date of the Request",
    "AdditionalNotesFieldLabel": "Additional Notes",
    "DeliveryMethodFieldLabel": "Levering Methode",
    "DeliveryMethodFieldPlaceholder": "Geef de Levering Methode voor de aanvraag",
    "CorrectionDefinitionFieldLabel": "Correction Definition",
    "DeliveryFormatFieldLabel": "Delivery Format",
    "DeliveryFormatFieldPlaceholder": "Provide the Delivery Format for the Request",
    "PersonalDataFieldLabel": "Personal Data",
    "ProcessingTypeFieldLabel": "Processing Type",
    "ProcessingTypeFieldPlaceholder": "Provide the Processing Type for the Request",
    "ReasonFieldLabel": "Reason",
    "NotifyApplicableFieldLabel": "Notify Applicable Controllers /Processors & Sub Processors",

    "SaveButtonText": "Opslaan",
    "CancelButtonText": "Annuleren",
    "ItemSavedMessage": "Item opgeslagen!",
    "InsertNextLabel": "Volgende toevoegen",
    "GoHomeLabel": "Terug naar homepagina",
    "ItemInsertedDialogTitle": "Item toegevoegd",
    "ItemInsertedDialogSubText": "Uw item is toegevoegd. Nu kunt u nog een toevoegen, of u kunt terug gaan naar de homepagina.",
  }
});