define([], function() {
  return {
    "PropertyPaneDescription": "Omschrijving",
    "BasicGroupName": "Groep Naam",
    "DescriptionFieldLabel": "Omschrijving Veld",

    "YesText": "Yes",
    "NoText": "No",

    "EventTypeFieldLabel": "Kies Incident Type voor Persoonlijke gegevens",
    "EventTypeDataBreachLabel": "Datalek",
    "EventTypeIdentityRiskLabel": "Indentiteits risico",
    "EventTypeDataConsentLabel": "Data toestemming",
    "EventTypeDataConsentWithdrawalLabel": "Data toestemming intrekken",
    "EventTypeDataProcessingLabel": "Data Verwerken",
    "EventTypeDataArchivedLabel": "Data Archiveren",

    "TitleFieldLabel": "Titel",
    "TitleFieldPlaceholder": "Geef een titel voor het Event",
    "TitleFieldValidationErrorMessage": "De minimale lengte van dit veld is 10 characters.",
    "NotifiedByFieldLabel": "Op de hoogte gesteld door?",
    "NotifiedByFieldPlaceholder": "Geef aan door wie jou op de hoogte heeft gebracht van die incident.",
    "NotifiedByFieldValidationErrorMessage": "De minimale lengte van dit veld is 5 characters.",
    "EventAssignedToFieldLabel": "Incident toegewezen aan:",
    "EventAssignedToFieldPlaceholder": "Gaaf op aan wie jij dit incident toewijst. ",
    "EventStartDateFieldLabel": "Wanneer is dit incident geconstateerd?",
    "EventStartDateFieldPlaceholder": "Geef start datum op van incident",
    "EventStartTimeHoursFieldLabel": "Uren",
    "EventStartTimeMinutesFieldLabel": "Minuten",
    "EventEndDateFieldLabel": "Wanneer verloopt het incident?",
    "EventEndDateFieldPlaceholder": "Geef een eind datum op van het incident",
    "EventEndTimeHoursFieldLabel": "Uren",
    "EventEndTimeMinutesFieldLabel": "Minuten",
    "PostEventReportFieldLabel": "Voorafgaand aan het incident",
    "AdditionalNotesFieldLabel": "Opmerkingen",
    "BreachTypeFieldLabel": "Data breuk/ lek type",
    "BreachTypeFieldPlaceholder": "Selecteer breuk type",
    "SeverityFieldLabel": "Ernst",
    "SeverityFieldPlaceholder": "Selecteer ernst hoogte",
    "DPANotifiedFieldLabel": "DPA genotificeerd",
    "DPANotificationDateFieldLabel": "DPA Notificatie Datum",
    "DPANotificationDateFieldPlaceholder": "Provide the DPA Notification date",
    "DPANotificationTimeHoursFieldLabel": "Hours",
    "DPANotificationTimeMinutesFieldLabel": "Minutes",
    "EstimatedAffectedSubjectsFieldLabel": "Estimated Number of Affected Data Subjects",
    "EstimatedAffectedSubjectsFieldValidationErrorMessage": "Please, provide a valid number",
    "ToBeDeterminedFieldLabel": "To Be Determined",
    "IncludesChildrenFieldLabel": "Includes Children",
    "IncludesChildrenInProgressFieldLabel": "In Progress",
    "ActionPlanFieldLabel": "Action Plan",
    "BreachResolvedFieldLabel": "Breach Resolved",
    "ActionsTakenFieldLabel": "Actions Taken",
    "RiskTypeFieldLabel": "Risk Type",
    "RiskTypeFieldPlaceholder": "Select the Risk Type",
    "IncludesSensitiveDataFieldLabel": "Includes Sensitive Data",
    "IncludesSensitiveDataFieldPlaceholder": "Select any included Sensitive Data",
    "DataSubjectIsChildFieldLabel": "Data Subject is Child",
    "IndirectDataProviderFieldLabel": "Indirect Data Provider",
    "DataProviderFieldLabel": "Data Provider",
    "ConsentNotesFieldLabel": "Consent Notes",
    "ConsentTypeFieldLabel": "Consent Type",
    "ConsentTypeFieldPlaceholder": "Select the Consent Types",
    "ConsentIsInternalFieldLabel": "Internal or External Data Subject",
    "InternalConsentText": "Internal",
    "ExternalConsentText": "External",
    "ConsentWithdrawalTypeFieldLabel": "Withdrawal Type",
    "ConsentWithdrawalTypeFieldPlaceholder": "Select the Withdrawal Type",
    "ConsentWithdrawalNotesFieldLabel": "Withdrawal Notes",
    "OriginalConsentAvailableFieldLabel": "Original Consent Available",
    "OriginalConsentFieldLabel": "Original Consent",
    "OriginalConsentFieldPlaceholder": "Select the Original Consent",
    "NotifyApplicableFieldLabel": "Notify Applicable Controllers /Processors & Sub Processors",
    "ProcessingTypeFieldLabel": "Processing Type",
    "ProcessingTypeFieldPlaceholder": "Select the Processing Type",
    "ProcessorsFieldLabel": "GDPR Processors",
    "ProcessorsFieldPlaceholder": "Select the GDPR Processors",
    "ArchivedDataFieldLabel": "Archived Data",
    "AnonymizeFieldLabel": "Anonymize",
    "ArchivingNotesFieldLabel": "Archiving Notes",

    "SaveButtonText": "Save",
    "CancelButtonText": "Cancel",
    "ItemSavedMessage": "Item saved!",
    "InsertNextLabel": "Insert next",
    "GoHomeLabel": "Go home",
    "ItemInsertedDialogTitle": "Item inserted",
    "ItemInsertedDialogSubText": "Your item has been inserted. Now you can add another one, or you can go back to the home page.",

    "HoursValidationError": "Please provide a valid hours value",
    "MinutesValidationError": "Please provide a valid minutes value",
  }
});