define([], function() {
  return {
    "PropertyPaneDescription": "Omschrijving",
    "BasicGroupName": "Groep Naam",
    "DescriptionFieldLabel": "Omschrijving Veld",

    "YesText": "Yes",
    "NoText": "No",

    "EventTypeFieldLabel": "Kies Incident Type voor Persoonlijke gegevens",
    "EventTypeDataBreachLabel": "Datalek",
    "EventTypeIdentityRiskLabel": "Indentiteits risico",
    "EventTypeDataConsentLabel": "Data toestemming",
    "EventTypeDataConsentWithdrawalLabel": "Data toestemming intrekken",
    "EventTypeDataProcessingLabel": "Data Verwerken",
    "EventTypeDataArchivedLabel": "Data Archiveren",

    "TitleFieldLabel": "Titel",
    "TitleFieldPlaceholder": "Geef een titel voor het Event",
    "TitleFieldValidationErrorMessage": "De minimale lengte van dit veld is 10 characters.",
    "NotifiedByFieldLabel": "Op de hoogte gesteld door?",
    "NotifiedByFieldPlaceholder": "Geef aan door wie jou op de hoogte heeft gebracht van die incident.",
    "NotifiedByFieldValidationErrorMessage": "De minimale lengte van dit veld is 5 characters.",
    "EventAssignedToFieldLabel": "Incident toegewezen aan:",
    "EventAssignedToFieldPlaceholder": "Gaaf op aan wie jij dit incident toewijst. ",
    "EventStartDateFieldLabel": "Wanneer is dit incident geconstateerd?",
    "EventStartDateFieldPlaceholder": "Geef start datum op van incident",
    "EventStartTimeHoursFieldLabel": "Uren",
    "EventStartTimeMinutesFieldLabel": "Minuten",
    "EventEndDateFieldLabel": "Wanneer verloopt het incident?",
    "EventEndDateFieldPlaceholder": "Geef een eind datum op van het incident",
    "EventEndTimeHoursFieldLabel": "Uren",
    "EventEndTimeMinutesFieldLabel": "Minuten",
    "PostEventReportFieldLabel": "Voorafgaand aan het incident",
    "AdditionalNotesFieldLabel": "Opmerkingen",
    "BreachTypeFieldLabel": "Data breuk/ lek type",
    "BreachTypeFieldPlaceholder": "Selecteer breuk type",
    "SeverityFieldLabel": "Ernst",
    "SeverityFieldPlaceholder": "Selecteer ernst hoogte",
    "DPANotifiedFieldLabel": "DPA genotificeerd",
    "DPANotificationDateFieldLabel": "DPA Notificatie Datum",
    "DPANotificationDateFieldPlaceholder": "Wanneer is de DPA op de hoogte gebracht?",
    "DPANotificationTimeHoursFieldLabel": "Uren",
    "DPANotificationTimeMinutesFieldLabel": "Minuten",
    "EstimatedAffectedSubjectsFieldLabel": "Geschat aantal betrokken data bronnen",
    "EstimatedAffectedSubjectsFieldValidationErrorMessage": "Geef obv een nr de hoeveelheid.",
    "ToBeDeterminedFieldLabel": "Nader te bepalen",
    "IncludesChildrenFieldLabel": "Bevat sub onderdelen",
    "IncludesChildrenInProgressFieldLabel": "Bezig",
    "ActionPlanFieldLabel": "Aktie Plan",
    "BreachResolvedFieldLabel": "Lek verholpen",
    "ActionsTakenFieldLabel": "Taken",
    "RiskTypeFieldLabel": "Risk Type",
    "RiskTypeFieldPlaceholder": "Selecteer het risico type",
    "IncludesSensitiveDataFieldLabel": "Bevat gevoelige data",
    "IncludesSensitiveDataFieldPlaceholder": "Selecteer eventueel opgenomen gevoelige gegevens",
    "DataSubjectIsChildFieldLabel": "Data onderwerp is sub onderdeelData Subject is Child",
    "IndirectDataProviderFieldLabel": "Indirecte gegevensprovider",
    "DataProviderFieldLabel": "Data Provider",
    "ConsentNotesFieldLabel": "Notities",
    "ConsentTypeFieldLabel": "Toestemmings Type",
    "ConsentTypeFieldPlaceholder": "Selecteer het toestemmings Types",
    "ConsentIsInternalFieldLabel": "Intern of extern gegevensonderwerp",
    "InternalConsentText": "Intern",
    "ExternalConsentText": "Extern",
    "ConsentWithdrawalTypeFieldLabel": "Terughaal Type",
    "ConsentWithdrawalTypeFieldPlaceholder": "Selecteer het terughaal type",
    "ConsentWithdrawalNotesFieldLabel": "Terughaal notities",
    "OriginalConsentAvailableFieldLabel": "Oorspronkelijke toestemming beschikbaar",
    "OriginalConsentFieldLabel": "Oorspronkelijke toestemming",
    "OriginalConsentFieldPlaceholder": "Selecteer het orginele toestemming akkoord",
    "NotifyApplicableFieldLabel": "Informeer toepasselijke controllers / processors en subprocessors",
    "ProcessingTypeFieldLabel": "Verwerkings Type",
    "ProcessingTypeFieldPlaceholder": "Selecteer het verwerkings type",
    "ProcessorsFieldLabel": "GDPR verwerkers",
    "ProcessorsFieldPlaceholder": "Selecteer de GDPR verrwerkers",
    "ArchivedDataFieldLabel": "Gearchiveerde data",
    "AnonymizeFieldLabel": "Anonimiseren",
    "ArchivingNotesFieldLabel": "Archivering notities ",

    "SaveButtonText": "Opslaan",
    "CancelButtonText": "Annuleer",
    "ItemSavedMessage": "Item opgeslagen!",
    "InsertNextLabel": "Plaats volgende",
    "GoHomeLabel": "Home",
    "ItemInsertedDialogTitle": "Item toegevoegd",
    "ItemInsertedDialogSubText": "Uw item is ingevoegd. Nu kunt u een nieuw item toevoegen, of u kunt teruggaan naar de startpagina.",

    "HoursValidationError": "Geef een geldige waarde op",
    "MinutesValidationError": "Please provide a valid minutes value",
  }
});